version: '3.4'

services:
  sourcingdb: 
    container_name: sourcingdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
   
  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
        - "1433:1433" 
    environment:
       ACCEPT_EULA: "Y"
       MSSQL_SA_PASSWORD: "231580606Me"
       
    
  esourcing.products:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
       - sourcingdb
    ports:
      - "8000:80"
    volumes:
      - ${Home}/ASP.NET/Https:/root/.aspnet/https/
      - ${Home}/.microsoft/usersecrets/:/root/.microsoft/usersecrets



  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    ports:
      - "8001:80"
    depends_on:
      - sourcingdb
      - rabbitmq
    volumes:
      - ${Home}/ASP.NET/Https:/root/.aspnet/https/
      - ${Home}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      

  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBus:HostName=rabbitmq"
    ports:
      - "8002:80"
    depends_on:
      - sourcingsqldb
      - rabbitmq
    volumes:
      - ${Home}/ASP.NET/Https:/root/.aspnet/https/
      - ${Home}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
  

  esourcing.apigateway:
    container_name: esourcingapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - esourcing.products
      - esourcing.sourcing
      - esourcing.order
    ports:
      - "5000:80"
    volumes:
      - ${Home}/ASP.NET/Https:/root/.aspnet/https/
      - ${Home}/.microsoft/usersecrets/:/root/.microsoft/usersecrets


  esourcing.ui:
    container_name: esourcingui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - sourcingsqldb
    ports:
      - "3000:80"
    volumes:
      - ${Home}/ASP.NET/Https:/root/.aspnet/https/
      - ${Home}/.microsoft/usersecrets/:/root/.microsoft/usersecret
